version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout
      - run: ./git-submodule-checkout.sh
      - run: ./install-gamma-cli.sh

workflows:
  version: 2
  build:
    jobs:
      - build
